Day02 Numpy

Fancy indexing:

Fancy Indexing (NumPy) means selecting multiple specific elements from an array using a list or array of indices instead of a single index or slice.



In [1]:
import numpy as np 

In [2]:
# fancy indexing 
# create a numpy array 
numbers = np.array([1,2,3,4,5,6,7,8])
print(numbers)

# select elements at index 1,2,6,7
elements = numbers[[1,2,6,7]]
print(elements)

[1 2 3 4 5 6 7 8]
[2 3 7 8]




Array Slicing (NumPy) is a technique used to extract a specific portion of an array using index ranges



In [3]:
# create a numpy array 
numbers = np.array([2,4,6,8,10,12,14])

# access the first 4 elements of the array
sliced_numbers = numbers[:5]
print(sliced_numbers)

[ 2  4  6  8 10]


In [4]:
# create a numpy array
numbers = np.array([2,4,6,7,8,14])

sliced_numbers = numbers[1:3] # [start:stop]
print(sliced_numbers)

[4 6]


In [ ]:
# create a numpy array
numbers = np.array([2,4,6,8,10,12,14])

# access the elements at even index
sliced_numbers = numbers[0::2] # [start:no end:step]
print(sliced_numbers)

# access every third element of the array
sliced_numbers = numbers[::3]

[ 2  6 10 14]


In [6]:
# Negative slicing 

# create a 1D numpy array
array = np.array([1,2,3,4,5,6])

# slice the last three elements of the array
sliced_array = array[-3:]
print(sliced_array)

[4 5 6]


In [7]:
arr = np.array([1,2,3,4,5,6])
# slice the array in reverse order 
slice_arr= arr[-1::-1]
print(slice_arr)

[6 5 4 3 2 1]


In [8]:
numbers = np.array([2,3,4,5,6,7])

# create a reversed array 
reversed_numbers = numbers[::-1]
print(reversed_numbers)

[7 6 5 4 3 2]


Array attributes:

Array attributes are built-in properties that provide information about a NumPy array such as its size, shape, dimensions, and data type.

Most common NumPy array attributes: ndim (dimensions), shape (array structure), size (total elements), dtype (data type), and itemsize (size of each element in bytes).

In [9]:
# create a Numpy array 
numbers = np.array([2,3,4,6,7,8,9])

# give the array dimension
print("Numberes of dimensions:",numbers.ndim)

# get shape of the array 
print("Shape:", numbers.shape)

Numberes of dimensions: 1
Shape: (7,)


In [17]:
numbers1 = np.array ([2,4,6,8,10,'a'])
print(numbers1)

print('Data types of first Array:', numbers1.dtype)

# create an array of int type 
int_numbers =np.array([2,4,6,10,12])


# create an array of float type 
float_numbers = np.array([3.4, 5.6,7.8,9.1])

# check data type of numbers
print('Data Types of second array:',int_numbers.dtype)

# create data tyoe of float array 
print ("Data types of third array:",float_numbers.dtype)

['2' '4' '6' '8' '10' 'a']
Data types of first Array: <U21
Data Types of second array: int64
Data types of third array: float64


We use (size attribute) to find the total number of elements in the array.

In [18]:
first = np.array([1,3,5,7,9,12])
second = np.array([1,2,3,6,10])

print("Size of first:", first.size)
print("Size of second:",second.size)

Size of first: 6
Size of second: 5


We use (itemsize arrtibute) to find the size(in bytes)of each element in the array.