In [1]:
import numpy as np



In [2]:
array = np.array([2,3,4,4])
print(array)

[2 3 4 4]


In [3]:
type(array)

numpy.ndarray

In [4]:
# numpy array of integer data
array =np.array([2,3,4])

In [5]:
type(array)

numpy.ndarray

In [6]:
array1 = np.array((1,2,3))
print(array1)
print (type(array1))

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
# create list of numbers
numbers = [2,3,4,5]
# create numpy arrray using numbers list
nparray = np.array(numbers)
print(nparray)

[2 3 4 5]


In [8]:
# create a tuples a number
numbers = (2,3,4,5)
# create numpy array using numbers tuple
nparray = np.array(numbers)
print(nparray)

[2 3 4 5]


In [9]:
# crate an array with 10 elements filled with zero
array = np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
type(array[2])

numpy.float64

In [11]:
# create a array with 15 elements filled with ones
numpy_array = np.ones(15)
print (numpy_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
type(numpy_array[1])

numpy.float64

np.arange()function in numpy works like python range()to create sequences of numbers. its syntax : np.arange (start, end step)

Start(optional):The stating number(default is 0).

end: The ending number (not included in the array).

step(optional): The diffence between number(default is 1).

In [13]:
array1 = range(10)
print(list(array1))
array2 = range(3,20,5)
print(list(array2))
array3 = range(3,20,2.5) # in range function we didn't use float value
print (array3)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[3, 8, 13, 18]


TypeError: 'float' object cannot be interpreted as an integer

In [14]:
# create array with valus from 0 to 9
array = np.arange(10)
print(array)

# create an array with valus form 3 to 20 with step of 2.3
array1 = np.arange(3,20,2.3)
print(array)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


np.linespace()function creates an array with evenly spaced numbers within a range. it's syntax is : np.linespace(start,end,num)

start:Starting value of the range.

end : Ending value of the range(inclusive).

num(optional): Number of values to create

In [15]:
print(np.linspace(0,10,5))

[ 0.   2.5  5.   7.5 10. ]


In [16]:
print(np.linspace(0,500,100))

[  0.           5.05050505  10.1010101   15.15151515  20.2020202
  25.25252525  30.3030303   35.35353535  40.4040404   45.45454545
  50.50505051  55.55555556  60.60606061  65.65656566  70.70707071
  75.75757576  80.80808081  85.85858586  90.90909091  95.95959596
 101.01010101 106.06060606 111.11111111 116.16161616 121.21212121
 126.26262626 131.31313131 136.36363636 141.41414141 146.46464646
 151.51515152 156.56565657 161.61616162 166.66666667 171.71717172
 176.76767677 181.81818182 186.86868687 191.91919192 196.96969697
 202.02020202 207.07070707 212.12121212 217.17171717 222.22222222
 227.27272727 232.32323232 237.37373737 242.42424242 247.47474747
 252.52525253 257.57575758 262.62626263 267.67676768 272.72727273
 277.77777778 282.82828283 287.87878788 292.92929293 297.97979798
 303.03030303 308.08080808 313.13131313 318.18181818 323.23232323
 328.28282828 333.33333333 338.38383838 343.43434343 348.48484848
 353.53535354 358.58585859 363.63636364 368.68686869 373.73737374
 378.787878

In [17]:
# elements between 10 and 100 with stepsize 4
array1 = np.arange(10,100,4)

# generate 4 elements between 10 and 100
array2 =np.linspace(10,100,4)

print("Using arange:",array1)#doesn't include 100
print("Using linspace:",array2)#includes 100

Using arange: [10 14 18 22 26 30 34 38 42 46 50 54 58 62 66 70 74 78 82 86 90 94 98]
Using linspace: [ 10.  40.  70. 100.]


numpy can also create arrays with random numbers using its random module.For example, we can use randint()to generate a random integer within a range.

In [18]:
# random number between 1 and 51
random_number = np.random.randint(1,51)
print(random_number)

# generate 10 random numbers between 1 and 51 
print (np.random.randint(1 , 51, 10))

7
[ 6 30 13 13 25 24 50 46 47 14]
