Standard deviation is a measure that tells us how spread out or scattered the data valus differ from the average or typical value.

In [111]:
import numpy as np 

In [112]:
# create a numpy array 
marks = np.array([86,83,82,81,85,84])

# compute the standard deviation of marks 
std_marks =np.std(marks)
print(std_marks)

1.707825127659933


In [113]:
# create an array
array1 =np.arange(1,101)
array1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [114]:
# compute the 50th percentile of the array 
result1 = np.percentile(array1,50)
print("50 percentile:",result1)
print("median value:",np.median(array1))

50 percentile: 50.5
median value: 50.5


In [115]:
print(np.percentile(array1, 75))

75.25


In [116]:
print(max(array1))
print(np.percentile(array1, 100))

100
100.0


In [117]:
# create an array 
array1 = np.array([2,4,9,16,27,26,91,84])

# find the minimum value of the array
min_val =np.min(array1)

# find the maximum value of the array
max_val =np.max(array1)

# print the results 
print ("Maximum value:", max_val)
print ("Minimum value:", min_val)

Maximum value: 91
Minimum value: 2


Numpy in N Dimension

In [118]:
import numpy as np

In [119]:
# create  2D array 
array1 = np.array ([[1,2,3],[4,5,6]])
print(array1.ndim)

# create 3D array 
array2 = np.array ([[[1,2],[3,4]],[[5,6],[7,8]]])
print(array2.ndim)

2
3


In [120]:
# create a 2D array with 3 rows and 4 colums 
list1 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]] 
print(list1)

np_array = np.array(list1)
print(np_array)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [121]:
# 2D array of inhomogeneous shape
array1=np.array ([[1,2,3],[4,5,6],[5,6,]])
print(array1)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [ ]:
# 2D array of homogeneous shape
array1=np.array ([[1,2,3],[4,5,6],[5,6,7]])
print(array1)

[[1 2 3]
 [4 5 6]
 [5 6 7]]


In [ ]:
# 2D array of different data types 
import numpy as np

array1 = np.array([
    [1, 2, 3],
    ['a', 'b', 'c'],
    [1.0, 2.0, 3.0]
])

print(array1)

[['1' '2' '3']
 ['a' 'b' 'c']
 ['1.0' '2.0' '3.0']]


In [ ]:

# create a 3D array with 2 "slice" of 3 row and 3 column 
import numpy as np

array3d = np.array([
    
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],

    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]

])

print(array3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [ ]:
# empty funcion --> The empty() function is used to create an array without initializing its values.
array2 = np.empty((2,3))

print(array2)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


In [ ]:
# create an empty 3-D array with 3 "slices" of 3 rows and 3 colume 
np_array = np.empty((3,3,3))
print(np_array)

[[[9.54724752e-312 9.54724817e-312 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000]]]


In [ ]:
# create  a 3x3x3 array filled with 1s
numpy_array =np.ones((2,3,4))
print(numpy_array)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
# create 2x2 array all filled with the value 9
array = np.full(shape= (2,2),fill_value = 9)
print("Array:\n", array)

Array:
 [[9 9]
 [9 9]]


In [ ]:
print(np.full((4,3),5))

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
# create 3D array all filled with the value 5

array3d = np.full((2,2,3), 5) #((blocks , rows , column),fill_value)

print(array3d)

[[[5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]]]


In [ ]:
# create an array with 5 rows and 3 columns 
arr = np.zeros((5,3))
print ("Array is :\n", arr)
print (" Dimension Array is :\n", arr.ndim)
print ("\n Shape Array is :", arr.shape)

Array is :
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
 Dimension Array is :
 2

 Shape Array is : (5, 3)


In [ ]:
# create a 3D array
import numpy as np

np_array = np.array([

    [[1,2],[3,4]],

    [[5,6],[7,8]],

    [[9,10],[11,12]]

])

print(np_array)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
# indexing array
print(np_array[2,0,0])

9


In [ ]:
print(np_array[1,0,1])

6


In [ ]:
print(np.arange(1,9))

[1 2 3 4 5 6 7 8]


In [ ]:
# using reshape function
np.arange(1,9).reshape(4,2) #  we need to (size of array = multiple of reshpe funcion )

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
array1 = np.arange(1, 25).reshape(4, 3, 2)
print(array1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]


In [ ]:
# slicing the 3-D array

entire_array = array1[:, :, :]#[blocks, rows, columns] ,: =  Take all 

# print("Entire Array:")
print(entire_array)  



[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]


In [ ]:
second_matrix = array1[1,:,:] #slice the second matrix
print(second_matrix)

[[ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
array= array1[:,1,:] #slice the second row of each matrix
print(array)

[[ 3  4]
 [ 9 10]
 [15 16]
 [21 22]]


In [ ]:
array = array1[:,:,1] #slice the second column of each matrix
#print(array)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]


Mutable->An object whose value can be changed after it is created.



In [ ]:
# using mutable
np_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np_array)

# change the value of element in second row and third column to 10
np_array[2,2]= 10
print(np_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


Reshape the array:

In [ ]:
array1 =np.array([1,3,5,7,2,4,6,8])
print(array1)

# reshape a 1D array into a 2D array with 2 rows and 4 column
result = np.reshape(array1, (2,4))
print("The reshape array is:")
print(result)

[1 3 5 7 2 4 6 8]
The reshape array is:
[[1 3 5 7]
 [2 4 6 8]]


In [ ]:
# create a array 
array1 = np.array([1,2,3,4,5,6,7,8,9])

# reshape the 1D array into a 3D array
result = np.reshape(array1, (1,3,3))

# print the new array
print ("1D to 3D array:\n",result)

1D to 3D array:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


Matrix-> A matrix is a two-dimension array where numbers are arranged into rows and colums.

In [ ]:
import numpy as np

In [ ]:
# create a 2x2 matrix
matrix1 =np.array([[1,2],
                   [3,5]])
print("2x2 matrix:\n",matrix1)

2x2 matrix:
 [[1 2]
 [3 5]]


In [ ]:
# create a 2D matrix 
matrix1 = np.matrix ([[1,2],[3,4]])
print(matrix1)
print(type(matrix1))

# create a 2d array
matrix2 =np.array([[1,2],[3,4]])
print(matrix2)
print(type(matrix2))

[[1 2]
 [3 4]]
<class 'numpy.matrix'>
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


Matrix Multiplication 


In [ ]:
# create a NumPy arrays 
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])
print(array1)
print()
print(array2)
print("Array multiplication:\n",array1*array2)
print("Array power:\n",array1**2)


[[1 2]
 [3 4]]

[[5 6]
 [7 8]]
Array multiplication:
 [[ 5 12]
 [21 32]]
Array power:
 [[ 1  4]
 [ 9 16]]


In [ ]:
# create Numpy matrices 
matrix1= np.matrix([[1,2],[3,4]])
matrix2= np.matrix([[3,0],[6,5]])
print(matrix1)
print()
print(matrix2)
print("Matrix multiplication:\n",matrix1 * matrix2)
print("Matrix power:\n",matrix1**2)

[[1 2]
 [3 4]]

[[3 0]
 [6 5]]
Matrix multiplication:
 [[15 10]
 [33 20]]
Matrix power:
 [[ 7 10]
 [15 22]]


In [ ]:
# create two matrices 
matrix1 = np.array([[6,7],
                    [8,9]])
matrix2 = np.array([[1,3],
                    [5,7]])

# calculate the dot product of the two matrices
result = np.dot(matrix1,matrix2)
print("matrix1 x matrix2:\n",result)
print(type(result))

matrix1 x matrix2:
 [[41 67]
 [53 87]]
<class 'numpy.ndarray'>


In [ ]:
matrix1 @ matrix2

array([[41, 67],
       [53, 87]])

In [ ]:
# create two matrices of incompltible dimension 
matrix1 = np.array([[1,2,3],
                    [4,5,6]])
matrix2 = np.array([[7,8],
                    [9,10]])
# attempt to calculate the dot prodct 
result = np.dot(matrix1 , matrix2)
print(result)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
# create two matrices of compltible dimension 
matrix1 = np.array([[1,2,3],
                    [4,5,6]])
matrix2 = np.array([[7,8],
                    [9,10]])
# attempt to calculate the dot prodct 
result = np.dot(matrix2 , matrix1)
print(result)

[[39 54 69]
 [49 68 87]]


In [ ]:
# create a matrix
matrix1 = np.array([[1,2],
                    [3,4]])
# get transpose of matrix1
result = np.transpose(matrix1)
print(result)

[[1 3]
 [2 4]]


In [ ]:
# create a 2x2 identity matrix using eye()
matrix1 = np.eye(2)

print("\n2x2 Identity Matrix:\n",matrix1)

# create a 3x3 identity matrix using identity()
matrix2 = np.identity(3)
print("3x3 Ideintity Matrix:\n", matrix2)


2x2 Identity Matrix:
 [[1. 0.]
 [0. 1.]]
3x3 Ideintity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



More NumPy array operation
 1) Filter
 2) NumPy where()
 3) NumPy any()
 4) Numpy all()
 5) NumPy stack()
 6) NumPy sum()/ mean()
 7) NumPy Masked Array
 8) NumPy flatten()

In [ ]:
import numpy as np

In [ ]:
array1 = np.array([[1,2,-1,-2,10,12,20],
                   [1,2,3,-6,1,-10,-1]])
print ("Original array:\n", array1)

print("Identify Negative values:")
print(array1<0)

Original array:
 [[  1   2  -1  -2  10  12  20]
 [  1   2   3  -6   1 -10  -1]]
Identify Negative values:
[[False False  True  True False False False]
 [False False False  True False  True  True]]


In [ ]:
array1 = np.array([[1,2,-1,-2,10,12,20],
                   [1,2,3,-6,1,-10,-1]])
print ("Original array:\n", array1)

print("Identify non-Negative values:")
print(array1>=0)

Original array:
 [[  1   2  -1  -2  10  12  20]
 [  1   2   3  -6   1 -10  -1]]
Identify non-Negative values:
[[ True  True False False  True  True  True]
 [ True  True  True False  True False False]]


In [ ]:
# filtered array
array1 = np.array([[1,2,-1,-2,10,12,20],
                   [1,2,3,-6,1,-10,-1]])
filtered_arr = array1[array1>0]
print("Positive values are:",filtered_arr)

Positive values are: [ 1  2 10 12 20  1  2  3  1]


In [ ]:
# using where() function for replace the value
array1 = np.array([[1,2,-1,-2,10,12,20],[1,2,3,-6,1,-10,-1]])

# replace negative values with 0
print(np.where(array1<0,0,array1))


[[ 1  2  0  0 10 12 20]
 [ 1  2  3  0  1  0  0]]


In [ ]:
# replace non-negative values with 1 and negative value with 0
print(np.where(array1>0,1,0))


[[1 1 0 0 1 1 1]
 [1 1 1 0 1 0 0]]


In [ ]:
array1 = np.array([1,2,3,4,5,6,7])

# if element is less than 2 or greater than 6, test condition is true 
test_condition1 = (array1<2)|(array1>6)

# select element of x if test condition is True 
#return 0 if test condition is false 
result1 = np.where(test_condition1,array1 , 0)
print(result1)

[1 0 0 0 0 0 7]


In [ ]:
# using any()function
array1=np.array([1,2,3,4,5])
# check if any element is smaller than 3
result = np.any(array1<3)
print(result)

True


In [ ]:
# check if any element is negative 
result = np.any(array1<0)
print(result)

False


In [ ]:
array1= np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
# check if any element in each row is greater than 5
result_row = np.any(array1>5, axis= 1)# 1->row
print(result_row)

# check if any element in each column is less than 3
result_column = np.any(array1<3, axis=0) #0->column
print(result_column)

[False  True  True]
[ True  True False]


In [ ]:
# using all() funcion
array1 = np.array([1,2,3,4,5])

# check if all element is greater than 2
result = np.all(array1>2)
print(result)

# check if all element is less than 8
result = np.all(array1<8)
print(result)

False
True


In [ ]:
array1 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

# check if all element in each row is greater than 5
result_row = np.all (array1>5,axis=1)
print(result_row)

# check if all element in each column is less then 10
result_column = np.all(array1<10,axis=0)
print(result_column)

[False False  True]
[ True  True  True]


In [ ]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array3 = np.array([7,8,9])
print("array1:\n",array1)
print("array2:\n",array2)
print("array3:\n",array3)
result = np.stack((array1,array2,array3), axis=0)
print("Result:\n",result)

array1:
 [1 2 3]
array2:
 [4 5 6]
array3:
 [7 8 9]
Result:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Stack operation is used to join a sequence of arrays into a new matrix

In [ ]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
print("array1:\n",array1)
print("array2:\n",array2)
result = np.stack((array1,array2), axis=1)
print("Result:\n",result)

array1:
 [1 2 3]
array2:
 [4 5 6]
Result:
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

# calculate the sum along columns (asix 0)
col= np.sum(array1, axis=0)
print("Sum along columns:")
print(col)

# calculate the average along columns (axis 0)
col= np.mean(array1, axis=0)
print("Average along columns:")
print(col)

Sum along columns:
[12 15 18]
Average along columns:
[4. 5. 6.]


Masked array is like an ordinary Numpy array where some values are masked or ignored 

Masked arrays are useful when working with datasets that contain invalid, missing, or unwanted values 

In [122]:
import numpy as np

In [ ]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

# create  a condition 
m = array1>5

In [124]:
m

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [126]:
# apply the filtering to the array 
ma =array1[m]
print("Orginal array:\n",array1)
print("filtered array:\n",ma)

Orginal array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
filtered array:
 [6 7 8 9]


In [127]:
from numpy.ma import MaskedArray

In [128]:
# create a Numpy array 
array1=np.array([1,2,3,4,5])

# create a mask based on a condition 
mask= array1>2

# create a maskedarray using the orginal array and the mask
masked_arr= MaskedArray(array1,mask)

print("Orginal array:\n",array1)
print("Masked array:\n",masked_arr)

Orginal array:
 [1 2 3 4 5]
Masked array:
 [1 2 -- -- --]


In [129]:
## Scaler Broadcasting
# An array with a smaller shape is expanded to match the shape of a larger one. This is called broadcasting.
array1 = np.array([0,1,2])
array2 = np.array([[6],[8],[9]])

# add arrays of different dimension 
# size of array1 expands to match with array2
result= array1 + array2
print(result)

[[ 6  7  8]
 [ 8  9 10]
 [ 9 10 11]]


In [130]:
# 1D array 
array1 = np.array([1,2,3])

# scalar 
number = 5

# add  scalar and 1D array
sum = array1 + number
print(sum)

[6 7 8]


In [ ]:
array1 = np.array([1,2,3,4,5])
number = 10

# number minus up with each array element
result = array1-number
print(result)

[-9 -8 -7 -6 -5]
